spring.application.name=EventPlanner
spring.datasource.url=jdbc:mysql://localhost:3306/eventplannerdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.port=8080
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
razorpay.key.id=rzp_test_RmjsOUdrenD0Gr
razorpay.key.secret=iFGjBT3HCOwuYs9AEnuaJrM9
gemini.api.key=YOUR_API_KEY
